### ISSUE TITLE
Blacklist http services & Redis clarification

### ISSUE THREAD

**Issue by TheBambino** [popstarfreas/Dimensions#72]
I'm not too familiar with using blacklist http services. Could you give an example of some of these? I was googling for a while, but the only one I could find that provided an API was [Hetrix Tools](https://hetrixtools.com).

Also, can you please give a bit more information on the purpose of Redis? You noted that is was for Pub/Sub for detached reloading, but what is that in the context of Dimensions.

**Comment by popstarfreas** [comment]
https://github.com/popstarfreas/Dimensions/blob/dev/app/node_modules/dimensions/blacklist.ts#L33
The one built-in isn't something I use anymore though. For specifically checking things like vpn/proxy I found this list of services:
  - 'proxycheck' (proxycheck.io)
  - 'iptrooper'
  - 'ipqualityscore'
  - 'getipintel'
  - 'iphub'
  - 'iphunter'
  - 'vpnblocker'
  - 'ip2proxy'
  - 'shodan'
  - 'teoh'
  - 'ipwarner'

Ranked from best to worst according to the source I got it from.

If you update line 33 and the response parser function from https://github.com/popstarfreas/Dimensions/blob/dev/app/node_modules/dimensions/blacklist.ts#L56 you could use something like proxycheck.io which gives you 1000 free requests per day, to check IPs for whether they are a proxy/vpn/server. obviously you don't want to exceed the limit otherwise you run into the decision of what to do when you hit it.

When you run dimensions as a service, in a cluster mode or distributed (but using the same volume) then it was just simple to use redis for publishing a message that each instance would receive and do the corresponding operation, like reloading from the config or reloading command handlers. Detached just means that the console you use isn't attached to the process so you can reload it essentially "remotely" (through redis). That's what `node dimensions_cli.js` is for.
